### ISSUE TITLE
Add class to dates in range

### ISSUE THREAD

**Issue by vlio20** [monterail/angular-mighty-datepicker#11]
Hi,  
Can you please add a class to dates which are placed between the start and the end date of a selected range?

**Comment by jandudulski** [comment]
Hi @vlio20, can you prepare a pull request for that?

**Comment by vlio20** [comment]
@jandudulski take a look at my repo https://github.com/outbrain/pure-angular-date-range-picker

**Comment by korzeniowski** [comment]
I believe this has already been added in 333cf6d83204c166f4d4488a71ab601a9134a9ab.
