### ISSUE TITLE
Why can't i filter by iterating over an array?

### ISSUE THREAD

**Issue by HarrisRobin** [monterail/angular-mighty-datepicker#12]
Hi,

First of all, great and very clean directive! I ran into an issue when trying to filter out available dates in the directive. I tried the following:

```
var _filter_available_dates = function(day) {
      _.forEach($scope.event.occurrences, function(occurrence) {
        if(day.isSame(moment(occurrence.event_date))) {
          console.log('day', day.day(), moment(occurrence.event_date).day());
          return true;
         //return day.day();
        }
      });
    }

$scope.calendarOptions = {
      start: moment().add('month', -1),
      months: 1,
      mode: "multiple",
      callback: _selectedDate,
      filter: _filter_available_dates
    };

```

So the idea is that I would iterate over every day in my event's array, wrap it in a moment object and check if it's the same day as the day returned from the directive. If it is, i would return day.day().

This does not work and instead the entire calendar is greyed out even though I have matches.
Any ideas why?

Thank you!
<img width="977" alt="screenshot 2015-10-30 23 09 02" src="https://cloud.githubusercontent.com/assets/3880008/10861566/3b4344bc-7f5b-11e5-80b2-b8d5e8085d5f.png">

**Comment by jandudulski** [comment]
@venticco @Belir can you help with that?

**Comment by HarrisRobin** [comment]
@jandudulski i solved my issue in some other way, but it's too bad you cannot do this because this is the simplest date picker i found out of the other ones that are over complicated for nothing.

**Comment by krabex** [comment]
@HarrisRobin I reproduced locally your issue and this behaviour is not a bug in angular-mighty-datepicker, but the way you wrote _filter_available_dates method. Lets take a look at your code:
```
_.forEach($scope.event.occurrences, function(occurrence) {
        if(day.isSame(moment(occurrence.event_date))) {
          console.log('day', day.day(), moment(occurrence.event_date).day());
          return true;
        }
      });
```
The _return true;_ is connected with anonymous function you passed to _forEach_, so it does not affect 
_filter_available_dates. Here you've got example code which you can easly adapt to you problem:
```
var _filter_available_dates = function(day) {
   var eventDates = [moment().add(2, 'day'), moment().add(-1, 'day')];
   return eventDates.some(function(ed) {
       return day.day() == ed.day()
   });
 }
```
