### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: eProvider <- e <- mightyDatepickerDirective

### ISSUE THREAD

**Issue by Jaspur** [monterail/angular-mighty-datepicker#13]
Error: $injector:unpr
Unknown Provider
```Unknown provider: eProvider <- e <- mightyDatepickerDirective```

**Comment by fracz** [comment]
Did you annotate your function? Seems like minification problem.

**Comment by jandudulski** [comment]
Hi @Jaspur, is this still an issue?

**Comment by Jaspur** [comment]
Fixed by the finally merged #8 ;-) Thnx
