### ISSUE TITLE
Missing week in January 2016

### ISSUE THREAD

**Issue by wojtekmaciej** [monterail/angular-mighty-datepicker#15]
Please look to the image
https://monosnap.com/file/LIjZOLvqxiLfqYYlQSywO8FtkROhVH

**Comment by AxelBazookas** [comment]
I managed to fix this by adding the following _buildMonth:
```
if (weeksInMonth < 0) {
  calendarStart.subtract(1,'day'); // HACK make sure the "weeksInYear" gets the weeks of last year
  weeksInMonth = (calendarStart.weeksInYear() - calendarStart.week()) + calendarEnd.week();
}
```

Around this line:
https://github.com/monterail/angular-mighty-datepicker/blob/master/build/angular-mighty-datepicker.js#L129

**Comment by metrox** [comment]
We fix it by setting fixed amount of weeks in month that will be displayed, It's common solution. @AxelBazookas you solution solve problem with january but unfortunately make problems with december (2014 as I remember).
