### ISSUE TITLE
Selecting a single date doesn't work for date ranges

### ISSUE THREAD

**Issue by gligoran** [monterail/angular-mighty-datepicker#19]
I cannot select the same date in the "Double datepicker for date range" demo on http://monterail.github.io/angular-mighty-datepicker/.

Right in the beginning, I can select today's date on the left picker, but not on the right one. If I then select yesterday's date on the left picker, I can select today on the right and left. If I then click on tomorrow's date on the right picker, I can't select today on the right or tomorrow on the left. So in essence, it half-works in the start, but after some clicking around, it stops working on both sides.

I had it working with change ```before``` and ```after``` attributes, but that brakes the ```rangeFrom``` and ```rangeTo``` functionality.

It would be awesome if this could be fixed.

**Comment by jandudulski** [comment]
@Belir could you release new version and update demo page?

**Comment by Belir** [comment]
Merged
