### ISSUE TITLE
Sample project not working 

### ISSUE THREAD

**Issue by pucchur** [monterail/angular-mighty-datepicker#2]
downloaded the project but the index.html is test folder is not showing the calendar

**Comment by hodak** [comment]
You have to run `$ bower install` in the root directory, it will fetch all the required dependencies. It's not in README, sorry, will add it today.

**Comment by pucchur** [comment]
Actually I did that just now, but still the index.html is not showing the datepicker

**Comment by hodak** [comment]
Hm that's strange, I just went through setting it up from scratch and it worked. Does JavaScript console show any errors?

**Comment by pucchur** [comment]
load resource: net::ERR_FILE_NOT_FOUND for all the dependencies

**Comment by hodak** [comment]
So it does look like bower-related issue. Has running `$ bower install` created `bower_components/` directory? Has it ran without any errors? It's the output for me after which it worked:

```bash
⌘ ~/monterail/angular-mighty-datepicker [master] > bower install
bower angular#>= 1.2            cached git://github.com/angular/bower-angular.git#1.4.3
bower angular#>= 1.2          validate 1.4.3 against git://github.com/angular/bower-angular.git#>= 1.2
bower moment#~2.6.0             cached git://github.com/moment/moment.git#2.6.0
bower moment#~2.6.0           validate 2.6.0 against git://github.com/moment/moment.git#~2.6.0
bower angular-bindonce#*        cached git://github.com/Pasvaz/bindonce.git#0.3.3
bower angular-bindonce#*      validate 0.3.3 against git://github.com/Pasvaz/bindonce.git#*
bower moment-range#~1.0.1       cached git://github.com/gf3/moment-range.git#1.0.9
bower moment-range#~1.0.1     validate 1.0.9 against git://github.com/gf3/moment-range.git#~1.0.1
bower moment#>= 1               cached git://github.com/moment/moment.git#2.10.6
bower moment#>= 1             validate 2.10.6 against git://github.com/moment/moment.git#>= 1
bower moment-range#~1.0.1      install moment-range#1.0.9
bower angular-bindonce#*       install angular-bindonce#0.3.3
bower moment#~2.6.0            install moment#2.6.0
bower angular#>= 1.2           install angular#1.4.3

moment-range#1.0.9 bower_components/moment-range
└── moment#2.6.0

angular-bindonce#0.3.3 bower_components/angular-bindonce

moment#2.6.0 bower_components/moment

angular#1.4.3 bower_components/angular
⌘ ~/monterail/angular-mighty-datepicker [master] > ls
LICENSE.txt             README.md               bower.json              bower_components        build                   gulpfile.js             package.json            src                     test
```

**Comment by pucchur** [comment]
Its says -- No bower.json file to save to,  .
Is that the error?

**Comment by hodak** [comment]
Yes, what directory are you in? You should be in project's root directory where `bower.json` is, not in `test/`

**Comment by pucchur** [comment]
yeah my index is now in the same location ... still not working ..
its still can't find my other files like anular and moment in bower

**Comment by pucchur** [comment]
![console](https://cloud.githubusercontent.com/assets/3825401/9110699/d3273aac-3c37-11e5-8bc7-c6dfa6af397d.jpg)

**Comment by hodak** [comment]
What do you mean index is in the same location? Structure should be like this:

```
⌘ ~/monterail/angular-mighty-datepicker [master] > tree -L 2
.
├── bower.json
├── bower_components
│   ├── angular
│   ├── angular-bindonce
│   ├── moment
│   └── moment-range
└── test
    └── index.html
```

It looks like `index.html` looks for `bower_components` in your user's home directory, not in project's directory. It must be in `test/index.html`.

**Comment by pucchur** [comment]
did that ..now a different problem is coming up
![console1](https://cloud.githubusercontent.com/assets/3825401/9110854/1728bda6-3c39-11e5-835e-7145f9b74abb.jpg)

**Comment by hodak** [comment]
Do you have [`build/`](https://github.com/monterail/angular-mighty-datepicker/tree/master/build) directory next to `bower_components/`?

**Comment by pucchur** [comment]
fixed it .. thanks a million

**Comment by hodak** [comment]
No problem, glad it works ;)
