### ISSUE TITLE
Deprecation warning: moment().add(period, number) is deprecated.

### ISSUE THREAD

**Issue by gligoran** [monterail/angular-mighty-datepicker#20]
I'm getting this warning in the console:

> Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

I'm not sure with which Moment.js version this came with, but should probably be updated.

**Comment by Jaspur** [comment]
:+1:

**Comment by renege** [comment]
+1

```
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).
```

I had to downgrade my moment.js
